### ISSUE TITLE
Not Working - No certificate - VTT 0.8.8 Dnde5 1.3.6

### ISSUE THREAD

**Issue by Niclasp1501** [ardittristan/VTTExternalActorViewer#14]
Hello this module is not working with VTT 0.8.8 Dnde5 1.3.6
i tested it with different actors
can you help?
![image](https://user-images.githubusercontent.com/44606632/126194141-8f22d540-d0e8-49f7-a047-8528d2dc207b.png)
![image](https://user-images.githubusercontent.com/44606632/126194271-1e427ca8-9bc8-438f-b37e-9c2aa2e3bf98.png)

**Comment by Niclasp1501** [comment]
with Dyndns or an external IP it doesn't work either

**Comment by McMuffin88** [comment]
Same Problem here

**Comment by ardittristan** [comment]
192.168 is a localhost address, since the site uses an online proxy it won't work with local ips. Though the site doesn't work with ips at all, only with dns sites. It should work when using an external dns though...

the direct link in the browser doesn't work because the viewer splits the link on the page. If you remove everything after .json on the link the 2nd image should at least show something in the browser.

(the url is `data url` + `actorid`)

**Comment by ardittristan** [comment]
Though there seem to also be issues with the proxy atm, let me check

**Comment by ardittristan** [comment]
nvm, seems to work fine, was using a coc character on a dnd5e sheet (whoops)

does it still not work when using a dns url (eg http://ardittristan.xyz/ ) to your server?

it sadly needs to be a publically accessible webpage (so from outside of your home network) since otherwise there would be no way to get the data without running into CORS (internet security) issues

**Comment by ardittristan** [comment]
I did update the site to log any errors in the console. if it still doesn't work when using a named url instead of ip url

**Comment by Niclasp1501** [comment]
Okay after I use duckdns and allow insecure content, the display works.
![image](https://user-images.githubusercontent.com/44606632/126211127-715a2a07-9d08-4a04-8e58-782bb333fa1c.png)

Unfortunately, I now have the problem that the translation from the dnde5 German module is not adopted and an English-language sheet is displayed again. Is there the possibility to translate a file in your module?

**Comment by ardittristan** [comment]
not right now, sorry, it's because I had to basically replicate the whole character sheet.
